### ISSUE TITLE
Improve runtime performance

### ISSUE THREAD

**Issue by ghost** [muhsinali/picture-gallery-scala#7]
Application generally appears to be slow at runtime (e.g. delete request takes 5-10s when it should be in the milliseconds). It seems that the Play app is waiting to connect to the database. Not sure why; this does not occur in the Java implementation of this web app.

**Comment by muhsinali** [comment]
Performance appears to be significantly affected by how pictures are stored in the database (currently stored as a bytes array). After reading more on this issue, it seems that storing the picture as a Base64 encoded string will speed up the application. This also removes the need for the action method `getPictureOfPlace()` in the `Application` controller class. Instead, Base64 encoded strings can be retrieved and embedded directly in the view html page.

However, the content type of the picture is also needed to correctly display the image on the web page. This will need to be stored in the Place class.
